//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lokanta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lokanta2Entities : DbContext
    {
        public Lokanta2Entities()
            : base("name=Lokanta2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Kategoriler> Kategoriler { get; set; }
        public DbSet<Masalar> Masalar { get; set; }
        public DbSet<Personeller> Personeller { get; set; }
        public DbSet<Siparisler> Siparisler { get; set; }
        public DbSet<Yemek_Secim> Yemek_Secim { get; set; }
        public DbSet<Yemekler> Yemekler { get; set; }
    }
}
